# Dependencies
markdown:         kramdown
#redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            FrenchTouch
tagline:          'Society advances when information goes faster from brain to brain'
description:      'One brick at a time to contribute to the DKIW pyramid fundation, documenting primary sources and the the procedures used similar to the pattern MVC are the required pipe documentation '
url:              http://frenchtouch.dev/
baseurl:          /

author:
  name:           'Sebas and Oberron'
  url:            https://frenchtouch.dev/Contact/

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/french-touch/frenchtouch
#version 3.a
plugins: [jekyll-paginate,kramdown]
