# Dependencies
markdown:         kramdown
#redcarpet
highlighter:      rouge.rb

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            FrenchTouch
tagline:          'Because the world needs depth'
description:      'Society advances when information goes faster from brain to brain'
url:              http://french-touch.dev
baseurl:          /

author:
  name:           'Sebas & Oberron'
  url:            https://frenchtouch.dev/Contact/

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/french-touch/frenchtouch
#version 3.a
plugins: [jekyll-paginate,kramdown]
