# Dependencies
markdown:         kramdown
#redcarpet
highlighter:      pygments.rb

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            FrenchTouch
tagline:          'Because the world needs depth'
description:      'A column that pairs analysis depth with uncomplicated words.'
url:              http://mattu/frenchtouch
baseurl:          /frenchtouch/

author:
  name:           'Sebas & Oberron'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
#version 3.a
plugins: [jekyll-paginate,kramdown,pygments.rb]
