# Dependencies
markdown:         kramdown
#redcarpet
highlighter:      rouge.rb

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            FrenchTouch
tagline:          'Society advances when information goes faster from brain to brain'
description:      'DKIW pyramid is the fundation, documented primary sources for Data and for the procedures used similar to the pattern MVC are the required pipe documentation '
url:              http://french-touch.dev
baseurl:          /

author:
  name:           'Sebas & Oberron'
  url:            https://frenchtouch.dev/Contact/

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/french-touch/frenchtouch
#version 3.a
plugins: [jekyll-paginate,kramdown]
