name: Notion2Pelican
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync_notion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : setup notion key
        env: # Or as an environment variable
          NotionKey: ${{ secrets.NotionKey }}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          if: ${{ env.NotionKey != '' }}
            run: echo "This command is executed if AWS_ACCESS_KEY_ID secret IS NOT empty"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout website source
        id: checkout-master
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          if: "${{ env.NotionKey != '' }}"
            run: echo "This command is executed if AWS_ACCESS_KEY_ID secret IS NOT empty"
